### ISSUE TITLE
AirDC++ settings section is ambiguous

### ISSUE THREAD

**Issue by rishighan** [rishighan/threetwo#39]
Upon trying to set up AirDC++ integration via the ThreeTwo Settings panel:

1. It is not obvious that a port number should be specified
2. Connection errors are not surfaced, causing confusion for the end user.

**Comment by nstephenh** [comment]
Furthermore, IP addresses are not allowed.

**Comment by rishighan** [comment]
In the latest build, the form lets you enter a hostname, IP, along with a port, protocol, username and password.
