### ISSUE TITLE
Can't connect to AirDC++

### ISSUE THREAD

**Issue by Trentflix** [rishighan/threetwo#40]
I'm attempting to connect to AirDC++ without success. I have the protocol, hostname, port, and creds correct. I've attempted to connect to AirDC++ running on a separate server as well as a local instance. I can connect to both AirDC++ instances using the web browser.

![unknown](https://user-images.githubusercontent.com/21056207/189499829-10a0f9f0-dfcd-45b8-8c03-66d891e4df37.png)

**Comment by rishighan** [comment]
Addressed in https://github.com/rishighan/threetwo/commit/eda11d3537aa6d4c121e49ccff2cbd14a6dffeaf and https://github.com/rishighan/threetwo-core-service/commit/c8492cb5aa24589f518c427f0587e03a41f1873f

**Comment by Trentflix** [comment]
I also confirmed late yesterday that with this change, this issue has been resolved. Thank you!

**Comment by rishighan** [comment]
Thanks @Trentflix! Closing.
