### ISSUE TITLE
Issues added from Comicvine with "Wanted" may have storyline name or "No Name"

### ISSUE THREAD

**Issue by nstephenh** [rishighan/threetwo#49]
If they have no name then there is no way to navigate to them.
If they have the storyline name, then "aquisition" defaults to that name. 
Consider instead "series_name issue (year)" or "series_name #issue"
Example would be Star Trek Lower Decks: https://comicvine.gamespot.com/star-trek-lower-decks-1-all-in-a-sea-of-wonders/4000-947280/

Issue 1 defaults as all in a sea of wonders and issues 2 and 3 don't have a name.

**Comment by rishighan** [comment]
@nstephenh Do you mean the comicvine search page or the acquisition panel on a comic issue's detail page?

**Comment by rishighan** [comment]
Fixed this.
