### ISSUE TITLE
Unable to extrapolate the hostname when running in Docker context

### ISSUE THREAD

**Issue by rishighan** [rishighan/threetwo#76]
@nstephenh Feel free to elaborate.

When running in a docker context, `threetwo-ui`'s `yarn run` command results in the hostname not been accessible from the host, with this:

```
threetwo-ui         |   ?  Local:   http://localhost:5173/
threetwo-ui         |   ?  Network: use --host to expose
```

**Comment by nstephenh** [comment]
Specifically it doesn't appear to be that the webui is accessible from devices other than localhost, but there could be something else wrong with my setup. Are you able to access it from across the network running from source?

From docker, I wouldn't expect even the host computer for the docker container would be able to access it unless the proxy network forwards traffic from localhost.

**Comment by rishighan** [comment]
My test setup is running the `docker-compose` `threetwo` stack on Unraid, and past that I use `unraidIP:<threetwo-ui-port>` to access the UI

**Comment by nstephenh** [comment]
Working now!
