### ISSUE TITLE
Discord/Docker Questions

### ISSUE THREAD

**Issue by kingfenix** [rishighan/threetwo#8]
1. The discord invite just says invalid invite when clicked.
2. Can you elaborate on docker instructions specifically for UNRAID users.

**Comment by rishighan** [comment]
1. I apologize, here's another one: https://discord.gg/Wcz89fKe
2. Unraid installation is currently only through Virtual Machines, which is documented [here.](https://rishighan.github.io/threetwo-docs/docs/unraid_install) This means that it is not available through the Community Apps, yet. Once ThreeTwo! hits 0.1 (March 2022), I'll release it to CA.

**Comment by kingfenix** [comment]
Thanks!
